name: "Submit Dependency Graph"
on:
  workflow_run:
    workflows: ["Main Workflow"]
    types:
      - completed
jobs:
  submit-dependency-graph:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4.1.2
      - uses: gradle/actions/dependency-submission@v3.2.0
        with:
          cache-encryption-key: ${{ secrets.GradleEncryptionKey }}
          dependency-graph: download-and-submit
