name: "Code Scan"
on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "30 4 * * *"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: ${{ !contains(github.ref, 'release/') }}
permissions:
  actions: read
  contents: read
  security-events: write
jobs:
  analyze:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        languages: [ "java-kotlin" ]
    steps:
      - uses: actions/checkout@v4.1.2
      - uses: github/codeql-action/init@v3.24.8
        with:
          languages: ${{ matrix.languages }}
          queries: security-extended
      - uses: github/codeql-action/autobuild@v3.24.8
      - uses: github/codeql-action/analyze@v3.24.8
