name: "Build"
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]
jobs:
  build:
    strategy:
      matrix:
        include:
          - { os: 'macos-latest', arch: 'x64', java-version: '11', gradle-version: '7.3' }
          - { os: 'ubuntu-latest', arch: 'x64', java-version: '11', gradle-version: '7.3' }
          - { os: 'windows-latest', arch: 'x64', java-version: '11', gradle-version: '7.3' }
    name: Gradle ${{ matrix.gradle-version }}, Java ${{ matrix.java-version }} on ${{ matrix.os }} (${{ matrix.arch }})
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Configure JDK ${{ matrix.java-version }} (${{ matrix.arch }})
        uses: actions/setup-java@v2
        with:
          architecture: ${{ matrix.arch }}
          distribution: 'temurin'
          java-version: ${{ matrix.java-version }}
      - uses: gradle/gradle-build-action@v2
        with:
          # Only write to the cache on the 'main' branch
          cache-read-only: ${{ github.ref != 'refs/heads/main' }}
          gradle-version: ${{ matrix.gradle-version }}
          arguments: build --scan
      - name: Upload build reports
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: build-reports-${{ matrix.os }}-${{ matrix.arch }}-jdk-${{ matrix.java-version }}
          path: |
            build/reports
            ./**/build/reports
