name: "Main Workflow"
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: ${{ !contains(github.ref, 'release/') }}
permissions:
  contents: read
jobs:
  build:
    strategy:
      matrix:
        os: ['macos-latest', 'ubuntu-latest', 'windows-latest']
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4.1.7
      - name: Configure JDKs
        uses: actions/setup-java@v4.5.0
        with:
          architecture: 'x64'
          distribution: 'temurin'
          java-version: |
            8
            11
            17
            21
      - name: Configure Gradle
        uses: gradle/actions/setup-gradle@v4.0.0
        with:
          validate-wrappers: true
          cache-encryption-key: ${{ secrets.GradleEncryptionKey }}
      - name: Execute build
        run: >
          ./gradlew build --info --console plain --no-daemon
          -D org.gradle.java.installations.auto-detect=true
          -D org.gradle.java.installations.auto-download=false
      - name: Upload reports
        uses: actions/upload-artifact@v4.3.4
        if: env.ACT != 'true' && always()
        with:
          name: ${{ matrix.os }}-build-reports-archive
          path: |
            build/reports
            ./**/build/reports
  upload-dependency-graph:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: gradle/actions/dependency-submission@v4.0.0
        with:
          cache-encryption-key: ${{ secrets.GradleEncryptionKey }}
          dependency-graph: generate-and-upload
