name: "Review PR"
on: [ pull_request ]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: ${{ !contains(github.ref, 'release/') }}
permissions:
  contents: read
jobs:
  validate-gradle-wrapper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: gradle/actions/wrapper-validation@v4.0.0
  review-dependencies:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: actions/dependency-review-action@v4.4.0
        with:
          comment-summary-in-pr: always
          retry-on-snapshot-warnings: true
          retry-on-snapshot-warnings-timeout: 600
          allow-dependencies-licenses: "pkg:maven/org.openjdk.nashorn/nashorn-core@15.4?type=jar"
          allow-licenses: Apache-2.0, MIT, EPL-2.0, BSD-3-Clause, 0BSD
  verify-no-whitespace-errors:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 0
      - name: git log --check
        env:
          fork_point: ${{ github.event.pull_request.base.sha }}
        run: |
          commit=
          errors=
          while read prefix remainder
          do
            case "${prefix}" in
            "---")
              commit="${remainder}"
              ;;
            "")
              ;;
            *)
              if test -n "${commit}"
              then
                errors="${errors}\n${commit}"
                echo "--- ${commit}"
              fi
              commit=
              errors="${errors}\n${prefix} ${remainder}"
              echo "${prefix} ${remainder}"
              ;;
            esac
          done <<< $(git log --check --pretty=format:"--- %h %s" ${fork_point}..)

          if test -n "${errors}"
          then
            exit 2
          fi
